spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
  datasource:
    url: jdbc:h2:mem:libraryH2
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

app:
  initSchemaFileName: jpa/001-create-initial-schema.sql
  updateSchemaFileName: jpa/002-update-schema.sql