spring:
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog.yaml
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true